version: "3.2"
services:
  flaresolver:
    container_name: flaresolver
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=106
      - PGID=112
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /mnt/data:/data
  sonarr:
    container_name: sonarr
    network_mode: host
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=106
      - PGID=112
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/data:/data
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=106
      - PGID=112
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /mnt/data:/data/media
  jackett:
    container_name: jackett
    image: cr.hotio.dev/hotio/jackett
    network_mode: host
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      - PUID=106
      - PGID=112
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - /docker/appdata/jackett:/config
  plex:
    image: cr.hotio.dev/hotio/plex
    container_name: plex 
    network_mode: host
    restart: unless-stopped
    volumes:
        - /docker/appdata/plex:/config
        - /mnt/data/media:/data/media
    environment:
        - PUID=106
        - PGID=112
        - UMASK=002
        - PLEX_CLAIM=claim-JR7jmE-ybxzVKxZffz1W
        - PLEX_PASS="yes"
    ports:
      - "32400:32400" 
  qbittorrent:
   container_name: qbittorrent
   image: cr.hotio.dev/hotio/qbittorrent
   network_mode: host
   restart: unless-stopped
   ports:
     - "8080:8080"
   environment:
     - PUID=106
     - PGID=112
     - UMASK=002
     - TZ=Etc/Stockholm
   volumes:
     - /docker/appdata/qbittorrent:/config 
     - /mnt/data/torrent:/data/torrent
  nginx:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    network_mode: host
    restart: unless-stopped
    volumes:
     - /docker/appdata/npm/data:/data
     - /docker/appdata/npm/lencr:/etc/letsencrypt
