version: "3.2"
services:
  lidarr:
    container_name: lidarr
    image: cr.hotio.dev/hotio/lidarr:latest
    restart: unless-stopped
    ports:
      - "8686:8686"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=Etc/Stockholm
    volumes:
      - ${APP_DATA}/lidarr:/config
      - ${MEDIA_FOLDER}:/data
  readarr:
    container_name: readarr
    restart: unless-stopped
    image: cr.hotio.dev/hotio/readarr:nightly
    ports:
      - "8787:8787"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=Etc/Stockholm
    volumes:
      - ${APP_DATA}/readarr:/config
      - ${MEDIA_FOLDER}:/data
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA}/radarr:/config
      - ${MEDIA_FOLDER}:/data
  sonarr:
    container_name: sonarr
    network_mode: host
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=Europe/Stockholm
    volumes:
      - ${APP_DATA}/sonarr:/config
      - ${MEDIA_FOLDER}:/data
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA}/bazarr:/config
      - ${MEDIA_FOLDER}:/data/media
  qbittorrent:
   container_name: qbittorrent
   image: cr.hotio.dev/hotio/qbittorrent:latest
   network_mode: host
   restart: unless-stopped
   ports:
     - "8080:8080"
   environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - UMASK=${UMASK}
     - TZ=Etc/Stockholm
   volumes:
     - ${APP_DATA}/qbittorrent:/config 
     - ${MEDIA_FOLDER}/torrent:/data/torrent
  nginx:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    network_mode: host
    restart: unless-stopped
    volumes:
     - ${APP_DATA}/npm/data:/data
     - ${APP_DATA}/npm/lencr:/etc/letsencrypt
  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:nightly
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=Etc/Stockholm
    volumes:
      - ${APP_DATA}/prowlarr:/config
  overseerr:
    container_name: overseerr
    image: cr.hotio.dev/hotio/overseerr:latest
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=Etc/Stockholm
    volumes:
      - ${APP_DATA}/overseerr:/config
