version: "3.2"
services:
  qbittorrent:
   container_name: qbittorrent
   image: lscr.io/linuxserver/qbittorrent:latest
   restart: unless-stopped
   ports:
     - "8080:8080"
     - "5225:5225"
   environment:
     - PUID=0
     - PGID=0
     - UMASK=${UMASK}
     - TZ=Europe/Stockholm
   volumes:
     - ${APP_DATA}/qbittorrent:/config 
     - ${MEDIA_FOLDER}/torrent:/downloads/
